/* eslint-disable @typescript-eslint/ban-ts-comment */
  /* eslint-disable @typescript-eslint/no-explicit-any */
  // @ts-nocheck
  // This file is autogenerated by scripts/build-registry.ts
  // Do not edit this file directly.

import React from "react";
import type { ComponentRegistry } from "./__registry";

export const components: ComponentRegistry = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: ["clsx","tailwind-merge"],
    files:     [
          {
                "path": "registry/lib/utils.ts",
                "type": "registry:lib",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/lib/utils");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "utils";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion": {
    name: "accordion",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files:     [
          {
                "path": "registry/ui/accordion.tsx",
                "type": "registry:ui",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/accordion");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accordion";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "avatar": {
    name: "avatar",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files:     [
          {
                "path": "registry/ui/avatar.tsx",
                "type": "registry:ui",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/avatar");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "avatar";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "alert-dialog": {
    name: "alert-dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: ["class-variance-authority"],
    files:     [
          {
                "path": "registry/ui/alert-dialog.tsx",
                "type": "registry:ui",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/alert-dialog");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "alert-dialog";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog": {
    name: "dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: ["class-variance-authority"],
    files:     [
          {
                "path": "registry/ui/dialog.tsx",
                "type": "registry:ui",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/dialog");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dialog";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: ["class-variance-authority"],
    files:     [
          {
                "path": "registry/ui/tabs.tsx",
                "type": "registry:ui",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/tabs");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tabs";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-area": {
    name: "scroll-area",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    files:     [
          {
                "path": "registry/ui/scroll-area.tsx",
                "type": "registry:ui",
                "target": ""
          }
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/ui/scroll-area");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-area";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-contained": {
    name: "accordion-contained",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: [{
      path: "components/examples/accordion-contained.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/accordion-contained");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accordion-contained";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-demo": {
    name: "accordion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: [{
      path: "components/examples/accordion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/accordion-demo");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accordion-demo";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "accordion-shadcn": {
    name: "accordion-shadcn",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: [{
      path: "components/examples/accordion-shadcn.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/accordion-shadcn");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "accordion-shadcn";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "alert-dialog-custom": {
    name: "alert-dialog-custom",
    description: "",
    type: "registry:example",
    registryDependencies: ["alert-dialog"],
    files: [{
      path: "components/examples/alert-dialog-custom.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/alert-dialog-custom");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "alert-dialog-custom";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "alert-dialog-demo": {
    name: "alert-dialog-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["alert-dialog"],
    files: [{
      path: "components/examples/alert-dialog-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/alert-dialog-demo");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "alert-dialog-demo";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "avatar-demo": {
    name: "avatar-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "components/examples/avatar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/avatar-demo");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "avatar-demo";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-custom": {
    name: "dialog-custom",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    files: [{
      path: "components/examples/dialog-custom.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/dialog-custom");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dialog-custom";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "dialog-demo": {
    name: "dialog-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["dialog"],
    files: [{
      path: "components/examples/dialog-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/dialog-demo");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "dialog-demo";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-area-demo-horizontal-scrolling": {
    name: "scroll-area-demo-horizontal-scrolling",
    description: "",
    type: "registry:example",
    registryDependencies: ["scroll-area"],
    files: [{
      path: "components/examples/scroll-area-demo-horizontal-scrolling.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/scroll-area-demo-horizontal-scrolling");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-area-demo-horizontal-scrolling";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "scroll-area-demo": {
    name: "scroll-area-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["scroll-area"],
    files: [{
      path: "components/examples/scroll-area-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/scroll-area-demo");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "scroll-area-demo";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-demo": {
    name: "tabs-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "components/examples/tabs-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/tabs-demo");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tabs-demo";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-ghost": {
    name: "tabs-ghost",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "components/examples/tabs-ghost.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/tabs-ghost");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tabs-ghost";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-shadcn": {
    name: "tabs-shadcn",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "components/examples/tabs-shadcn.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/tabs-shadcn");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tabs-shadcn";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-solid": {
    name: "tabs-solid",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "components/examples/tabs-solid.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/tabs-solid");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tabs-solid";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  },
  "tabs-underline": {
    name: "tabs-underline",
    description: "",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "components/examples/tabs-underline.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/components/examples/tabs-underline");
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "tabs-underline";
      return { default: mod.default || mod[exportName] };
    }),
    categories: undefined,
    meta: undefined,
  }
};
