import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_DIR = path.resolve(__dirname, "..");
const ROOT_DIR = path.resolve(PACKAGE_DIR, "../..");

const SOURCE_UI_DIR = path.join(ROOT_DIR, "apps/www/registry/ui");
const SOURCE_UTILS_FILE = path.join(ROOT_DIR, "apps/www/registry/lib/utils.ts");

const TARGET_UI_DIR = path.join(PACKAGE_DIR, "src/components/ui");
const TARGET_UI_INDEX_FILE = path.join(TARGET_UI_DIR, "index.ts");
const TARGET_UTILS_FILE = path.join(PACKAGE_DIR, "src/lib/utils.ts");

const IMPORT_REWRITES: Array<{ from: string; to: string }> = [
  { from: '"@/registry/ui/', to: '"./' },
  { from: "'@/registry/ui/", to: "'./" },
  { from: '"registry/ui/', to: '"./' },
  { from: "'registry/ui/", to: "'./" },
  { from: '"@/registry/lib/', to: '"../../lib/' },
  { from: "'@/registry/lib/", to: "'../../lib/" },
  { from: '"@/hooks/', to: '"../../hooks/' },
  { from: "'@/hooks/", to: "'../../hooks/" },
  { from: '"@/lib/utils"', to: '"../../lib/utils"' },
  { from: "'@/lib/utils'", to: "'../../lib/utils'" },
];

function rewriteImports(source: string): string {
  return IMPORT_REWRITES.reduce(
    (content, rewrite) => content.replaceAll(rewrite.from, rewrite.to),
    source,
  );
}

async function listTsxFiles(directory: string): Promise<string[]> {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".tsx"))
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b));
}

async function removeGeneratedTargetFiles(directory: string): Promise<void> {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  await Promise.all(
    entries.map(async (entry) => {
      if (!entry.isFile()) return;

      const shouldDelete =
        entry.name.endsWith(".tsx") ||
        entry.name === path.basename(TARGET_UI_INDEX_FILE);
      if (shouldDelete) {
        await fs.unlink(path.join(directory, entry.name));
      }
    }),
  );
}

async function syncUiComponents(): Promise<void> {
  await fs.access(SOURCE_UI_DIR);
  await fs.access(SOURCE_UTILS_FILE);

  await fs.mkdir(TARGET_UI_DIR, { recursive: true });
  await removeGeneratedTargetFiles(TARGET_UI_DIR);

  const sourceFiles = await listTsxFiles(SOURCE_UI_DIR);

  for (const fileName of sourceFiles) {
    const sourcePath = path.join(SOURCE_UI_DIR, fileName);
    const targetPath = path.join(TARGET_UI_DIR, fileName);

    const sourceContent = await fs.readFile(sourcePath, "utf8");
    const rewrittenContent = rewriteImports(sourceContent);

    await fs.writeFile(targetPath, rewrittenContent, "utf8");
  }

  const utilsContent = await fs.readFile(SOURCE_UTILS_FILE, "utf8");
  await fs.writeFile(TARGET_UTILS_FILE, utilsContent, "utf8");

  const exportLines = sourceFiles.map((fileName) => {
    const componentName = fileName.replace(".tsx", "");
    return `export * from "./${componentName}";`;
  });

  const indexContent = `// This file is auto-generated by packages/ui/scripts/sync-ui-components.ts\n// Do not edit manually.\n\n${exportLines.join("\n")}\n`;
  await fs.writeFile(TARGET_UI_INDEX_FILE, indexContent, "utf8");

  console.log(`Synced ${sourceFiles.length} UI components to ${TARGET_UI_DIR}`);
  console.log(`Synced utils helper to ${TARGET_UTILS_FILE}`);
  console.log(`Generated ${TARGET_UI_INDEX_FILE}`);
}

void syncUiComponents().catch((error) => {
  console.error("Failed to sync UI components:", error);
  process.exit(1);
});
