// @ts-nocheck -- skip type checking
import * as docs_5 from "../content/docs/components/badge.mdx?collection=docs&hash=1760396806095"
import * as docs_4 from "../content/docs/components/alert-dialog.mdx?collection=docs&hash=1760396806095"
import * as docs_3 from "../content/docs/components/accordion.mdx?collection=docs&hash=1760396806095"
import * as docs_2 from "../content/docs/(get-started)/introduction.mdx?collection=docs&hash=1760396806095"
import * as docs_1 from "../content/docs/(get-started)/installation.mdx?collection=docs&hash=1760396806095"
import * as docs_0 from "../content/docs/(get-started)/composition.mdx?collection=docs&hash=1760396806095"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"(get-started)/composition.mdx","fullPath":"content/docs/(get-started)/composition.mdx"}, data: docs_0 }, { info: {"path":"(get-started)/installation.mdx","fullPath":"content/docs/(get-started)/installation.mdx"}, data: docs_1 }, { info: {"path":"(get-started)/introduction.mdx","fullPath":"content/docs/(get-started)/introduction.mdx"}, data: docs_2 }, { info: {"path":"components/accordion.mdx","fullPath":"content/docs/components/accordion.mdx"}, data: docs_3 }, { info: {"path":"components/alert-dialog.mdx","fullPath":"content/docs/components/alert-dialog.mdx"}, data: docs_4 }, { info: {"path":"components/badge.mdx","fullPath":"content/docs/components/badge.mdx"}, data: docs_5 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"pages":["(get-started)","components"]}}, {"info":{"path":"(get-started)/meta.json","fullPath":"content/docs/(get-started)/meta.json"},"data":{"title":"Get Started","pages":["introduction","installation","composition"]}}])