// @ts-nocheck
import { default as __fd_glob_50 } from "../content/docs/components/layout-nav/meta.json?collection=docs"
import { default as __fd_glob_49 } from "../content/docs/components/overlays-dialogs/meta.json?collection=docs"
import { default as __fd_glob_48 } from "../content/docs/components/form-input/meta.json?collection=docs"
import { default as __fd_glob_47 } from "../content/docs/components/feedback-status/meta.json?collection=docs"
import { default as __fd_glob_46 } from "../content/docs/components/display-media/meta.json?collection=docs"
import { default as __fd_glob_45 } from "../content/docs/components/meta.json?collection=docs"
import { default as __fd_glob_44 } from "../content/docs/(get-started)/meta.json?collection=docs"
import { default as __fd_glob_43 } from "../content/docs/meta.json?collection=docs"
import * as __fd_glob_42 from "../content/docs/components/overlays-dialogs/tooltip.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/components/overlays-dialogs/preview-card.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/components/overlays-dialogs/popover.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/components/overlays-dialogs/menubar.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/components/overlays-dialogs/dropdown-menu.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/components/overlays-dialogs/dialog.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/components/overlays-dialogs/context-menu.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/components/overlays-dialogs/alert-dialog.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/components/misc/toolbar.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/components/misc/toggle.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/components/misc/toggle-group.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/components/misc/collapsible.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/components/layout-nav/tabs.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/components/layout-nav/separator.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/components/layout-nav/scroll-area.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/components/layout-nav/navigation-menu.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/components/layout-nav/menubar.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/components/layout-nav/accordion.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/components/form-input/switch.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/components/form-input/slider.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/components/form-input/select.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/components/form-input/radio-group.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/components/form-input/number-field.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/components/form-input/meter.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/components/form-input/input.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/components/form-input/form.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/components/form-input/fieldset.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/components/form-input/field.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/components/form-input/combobox.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/components/form-input/checkbox.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/components/form-input/checkbox-group.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/components/form-input/button.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/components/form-input/autocomplete.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/components/feedback-status/toast.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/components/feedback-status/progress.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/components/feedback-status/alert.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/components/display-media/avatar.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/themes/orchid.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/themes/celeste.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/(get-started)/introduction.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/(get-started)/installation.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/(get-started)/composition.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/(get-started)/components.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "content/docs", {"meta.json": __fd_glob_43, "(get-started)/meta.json": __fd_glob_44, "components/meta.json": __fd_glob_45, "components/display-media/meta.json": __fd_glob_46, "components/feedback-status/meta.json": __fd_glob_47, "components/form-input/meta.json": __fd_glob_48, "components/overlays-dialogs/meta.json": __fd_glob_49, "components/layout-nav/meta.json": __fd_glob_50, }, {"(get-started)/components.mdx": __fd_glob_0, "(get-started)/composition.mdx": __fd_glob_1, "(get-started)/installation.mdx": __fd_glob_2, "(get-started)/introduction.mdx": __fd_glob_3, "themes/celeste.mdx": __fd_glob_4, "themes/orchid.mdx": __fd_glob_5, "components/display-media/avatar.mdx": __fd_glob_6, "components/feedback-status/alert.mdx": __fd_glob_7, "components/feedback-status/progress.mdx": __fd_glob_8, "components/feedback-status/toast.mdx": __fd_glob_9, "components/form-input/autocomplete.mdx": __fd_glob_10, "components/form-input/button.mdx": __fd_glob_11, "components/form-input/checkbox-group.mdx": __fd_glob_12, "components/form-input/checkbox.mdx": __fd_glob_13, "components/form-input/combobox.mdx": __fd_glob_14, "components/form-input/field.mdx": __fd_glob_15, "components/form-input/fieldset.mdx": __fd_glob_16, "components/form-input/form.mdx": __fd_glob_17, "components/form-input/input.mdx": __fd_glob_18, "components/form-input/meter.mdx": __fd_glob_19, "components/form-input/number-field.mdx": __fd_glob_20, "components/form-input/radio-group.mdx": __fd_glob_21, "components/form-input/select.mdx": __fd_glob_22, "components/form-input/slider.mdx": __fd_glob_23, "components/form-input/switch.mdx": __fd_glob_24, "components/layout-nav/accordion.mdx": __fd_glob_25, "components/layout-nav/menubar.mdx": __fd_glob_26, "components/layout-nav/navigation-menu.mdx": __fd_glob_27, "components/layout-nav/scroll-area.mdx": __fd_glob_28, "components/layout-nav/separator.mdx": __fd_glob_29, "components/layout-nav/tabs.mdx": __fd_glob_30, "components/misc/collapsible.mdx": __fd_glob_31, "components/misc/toggle-group.mdx": __fd_glob_32, "components/misc/toggle.mdx": __fd_glob_33, "components/misc/toolbar.mdx": __fd_glob_34, "components/overlays-dialogs/alert-dialog.mdx": __fd_glob_35, "components/overlays-dialogs/context-menu.mdx": __fd_glob_36, "components/overlays-dialogs/dialog.mdx": __fd_glob_37, "components/overlays-dialogs/dropdown-menu.mdx": __fd_glob_38, "components/overlays-dialogs/menubar.mdx": __fd_glob_39, "components/overlays-dialogs/popover.mdx": __fd_glob_40, "components/overlays-dialogs/preview-card.mdx": __fd_glob_41, "components/overlays-dialogs/tooltip.mdx": __fd_glob_42, });