import {
  Activity,
  ArrowUpRight,
  Book,
  Component,
  Diamond,
  type LucideProps,
  Palette,
  Play,
} from "lucide-react";

export const IconMap: Record<string, React.ComponentType<LucideProps>> = {
  Book,
  Play,
  Component,
  Diamond,
  Palette,
  Activity,
  "Get Started": Book,
  Components: Diamond,
  "Form & Input": Diamond,
  "Layout & Navigation": Diamond,
  "Feedback & Status": Diamond,
  "Display & Media": Diamond,
  "Overlays & Dialogs": Diamond,
  Misc: Diamond,
  Themes: Palette,
  Introduction: Book,
  default: ArrowUpRight,
};
